### ISSUE TITLE
Presumably changes in BairesDev TimeTracker causes AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by edwin-navarrete** [eyscode/timetracker#14]
There is new columns in the form:  Assignment Type | Task Description | Task Category | Task
Hence:

tt load -d 02/08/2021 -h 0.5 -t "DAM | Daily"
Traceback (most recent call last):
  File "/usr/local/bin/tt", line 8, in <module>
    sys.exit(tt())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/timetracker/cli.py", line 52, in load
    load_hours(text, config, date, pto, vacations, hours)
  File "/usr/local/lib/python3.9/site-packages/timetracker/timetracker.py", line 274, in load_hours
    secrets, load_assigments_page = set_project(session, load_time_page, project_option)
  File "/usr/local/lib/python3.9/site-packages/timetracker/timetracker.py", line 124, in set_project
    _eventtarget = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by jrborbars** [comment]
Any thought about this?  Can I help?
